# This is a basic workflow to help you get started with Actions

name: Hello_Action

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains two jobs, this is Linux related job
  Linux_Job:
    # The type of runner that the job will run on
    needs: [Windows_Job]
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
  # This workflow contains two jobs, this is Windows related job
  Windows_Job:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners command prompt
      - name: Run a one-line script
        run: Get-Service
